[package]
name = "async-embedded-hal"
version = "0.0.1"
authors = ["Sjoerd Simons <sjoerd@luon.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
futures = { version = "0.3", default-features = false }
